# 19AI613 Machine Learning -Dr.S.Padmavathi, 2020-21 odd semester

In [22]:
#Creating a Vector
# Load library
import numpy as np
# Create a vector as a row
vector_row = np.array([1, 2, 3])
# Create a vector as a column
vector_column = np.array([[1],
[2],
[3]])
print(vector_column)


[[1]
 [2]
 [3]]


In [23]:
#Creating a Matrix
# Load library
import numpy as np
# Create a matrix
matrix = np.array([[1, 2],
[1, 2],
[1, 2]])
print(matrix)

[[1 2]
 [1 2]
 [1 2]]


In [3]:
#Creating a Sparse Matrix
# Load libraries
import numpy as np
from scipy import sparse
# Create a matrix
matrix = np.array([[0, 0],[0, 1], [3, 0]])
# Create compressed sparse row (CSR) matrix
matrix_sparse = sparse.csr_matrix(matrix)
# View sparse matrix
print(matrix_sparse)


  (1, 1)	1
  (2, 0)	3


In [25]:
#Selecting Elements
# Load library
import numpy as np
# Create row vector
vector = np.array([1, 2, 3, 4, 5, 6])
# Create matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Select third element of vector
vector[2]

3

In [6]:
# Select second row, second column
matrix[1,1]

5

In [8]:
# Select all elements of a vector
vector[:]

array([1, 2, 3, 4, 5, 6])

In [9]:
# Select everything up to and including the third element
vector[:3]

array([1, 2, 3])

In [10]:
# Select everything after the third element
vector[3:]

array([4, 5, 6])

In [11]:
# Select the last element
vector[-1]

6

In [27]:
# Select the first two rows and all columns of a matrix
matrix[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
# Select all elements of second column of a matrix
matrix[:,1:2]

array([[2],
       [5],
       [8]])

In [14]:
#Describing the shape, size, and dimensions of the matrix
# View number of rows and columns
matrix.shape

(3, 3)

In [15]:
# View number of elements (rows * columns)
matrix.size

9

In [16]:
# View number of dimensions
matrix.ndim

2

In [17]:
#Applying Operations to Elements
# Load library
import numpy as np
# Create matrix
matrix = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
# Create function that adds 100 to something
add_100 = lambda i: i + 100
# Create vectorized function
vectorized_add_100 = np.vectorize(add_100)
# Apply function to all elements in matrix
vectorized_add_100(matrix)


array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [18]:
matrix + 100


array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [28]:
#Finding the Maximum and Minimum Values
# Load library
import numpy as np
# Create matrix
matrix = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
# Return maximum element
np.max(matrix)


9

In [29]:
# Return minimum element
np.min(matrix)

1

In [30]:
# Find maximum element in each column
np.max(matrix, axis=0)


array([7, 8, 9])

In [31]:
# Find maximum element in each row
np.max(matrix, axis=1)


array([3, 6, 9])

In [32]:
#Calculating the Average, Variance, and Standard Deviation
# Return mean
np.mean(matrix)


5.0

In [33]:
# Return variance
np.var(matrix)


6.666666666666667

In [34]:
# Return standard deviation
np.std(matrix)


2.581988897471611

In [35]:
# Find the mean value in each column
np.mean(matrix, axis=0)


array([4., 5., 6.])

In [40]:
#Reshaping Arrays
# Load library
import numpy as np
# Create 4x3 matrix
matrix = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9],
[10, 11, 12]])
# Reshape matrix into 2x6 matrix
matrix.reshape(2, 6)


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

matrix.reshape(1,-1)

In [41]:
matrix.reshape(1,-1)


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [42]:
matrix.reshape(-1,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [43]:
matrix.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [44]:
#Transposing a Vector or Matrix
# Load library
import numpy as np
# Create matrix
matrix = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
# Transpose matrix
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [45]:
# Transpose vector
np.array([1, 2, 3, 4, 5, 6]).T

array([1, 2, 3, 4, 5, 6])

In [46]:
# Tranpose row vector
np.array([[1, 2, 3, 4, 5, 6]]).T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [47]:
#Flattening a Matrix
# Load library
import numpy as np
# Create matrix
matrix = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
# Flatten matrix
matrix.flatten()


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
matrix.reshape(1, -1)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [49]:
#Finding the Rank of a Matrix
# Load library
import numpy as np
# Create matrix
matrix = np.array([[1, 1, 1],
[1, 1, 10],
[1, 1, 15]])
# Return matrix rank
np.linalg.matrix_rank(matrix)

2

In [50]:
#Calculating the Determinant
# Load library
import numpy as np
# Create matrix
matrix = np.array([[1, 2, 3],
[2, 4, 6],
[3, 8, 9]])
# Return determinant of matrix
np.linalg.det(matrix)


0.0

In [51]:
#Getting the Diagonal of a Matrix
# Load library
import numpy as np
# Create matrix
matrix = np.array([[1, 2, 3],
[2, 4, 6],
[3, 8, 9]])
# Return diagonal elements
matrix.diagonal()


array([1, 4, 9])

In [52]:
# Return diagonal one above the main diagonal
matrix.diagonal(offset=1)


array([2, 6])

In [53]:
# Return diagonal one below the main diagonal
matrix.diagonal(offset=-1)


array([2, 8])

In [54]:
#Calculating the Trace of a Matrix
# Load library
import numpy as np
# Create matrix
matrix = np.array([[1, 2, 3],
[2, 4, 6],
[3, 8, 9]])
# Return trace
matrix.trace()


14

In [55]:
# Return diagonal and sum elements
sum(matrix.diagonal())


14

In [59]:
#Finding Eigenvalues and Eigenvectors
# Load library
import numpy as np
# Create matrix
matrix = np.array([[1, -1, 3],
[1, 1, 6],
[3, 8, 9]])
# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)
# View eigenvalues
eigenvalues



array([13.55075847,  0.74003145, -3.29078992])

In [58]:
# View eigenvectors
eigenvectors

array([[-0.17622017, -0.96677403, -0.53373322],
       [-0.435951  ,  0.2053623 , -0.64324848],
       [-0.88254925,  0.15223105,  0.54896288]])

In [36]:
#Calculating Dot Products
# Load library
import numpy as np
# Create two vectors
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])
# Calculate dot product
np.dot(vector_a, vector_b)


32

In [37]:
# Calculate dot product
vector_a @ vector_b


32

In [62]:
#Adding and Subtracting Matrices
import numpy as np
# Create matrix
matrix_a = np.array([[1, 1, 1],
[1, 1, 1],
[1, 1, 2]])
# Create matrix
matrix_b = np.array([[1, 3, 1],
[1, 3, 1],
[1, 3, 8]])
# Add two matrices
np.add(matrix_a, matrix_b)

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [63]:
# Subtract two matrices
np.subtract(matrix_a, matrix_b)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

In [64]:
matrix_a+ matrix_b

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [65]:
matrix_a- matrix_b

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

In [66]:
#Multiplying Matrices
# Load library
import numpy as np
# Create matrix
matrix_a = np.array([[1, 1],
[1, 2]])
# Create matrix
matrix_b = np.array([[1, 3],
[1, 2]])
# Multiply two matrices
np.dot(matrix_a, matrix_b)

array([[2, 5],
       [3, 7]])

In [67]:
matrix_a@ matrix_b

array([[2, 5],
       [3, 7]])

In [68]:
matrix_a*matrix_b

array([[1, 3],
       [1, 4]])

In [69]:
#Inverting a Matrix
# Load library
import numpy as np
# Create matrix
matrix = np.array([[1, 4],
[2, 5]])
# Calculate inverse of matrix
np.linalg.inv(matrix)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

In [70]:
matrix@ np.linalg.inv(matrix)

array([[1., 0.],
       [0., 1.]])

In [71]:
#Generating Random Values
import numpy as np
# Set seed
np.random.seed(0)
# Generate three random floats between 0.0 and 1.0
np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])

In [72]:
# Generate three random integers between 1 and 10
np.random.randint(0, 11, 3)

array([3, 7, 9])

In [73]:
# Draw three numbers from a normal distribution with mean 0.0
# and standard deviation of 1.0
np.random.normal(0.0, 1.0, 3)

array([-1.42232584,  1.52006949, -0.29139398])

In [74]:
# Draw three numbers greater than or equal to 1.0 and less than 2.0
np.random.uniform(1.0, 2.0, 3)

array([1.27265629, 1.47766512, 1.81216873])

In [75]:
# Draw three numbers from a logistic distribution with mean 0.0 and scale of 1.0
np.random.logistic(0.0, 1.0, 3)

array([-0.08013416, -0.4356214 ,  1.62933678])